
CREATE TABLE public.admin_usuarios (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  nome text not null,
  email text null,
  cargo text null
);

ALTER TABLE public.admin_usuarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all on admin_usuarios"
ON public.admin_usuarios FOR ALL
TO public
USING (true)
WITH CHECK (true);

ALTER TABLE public.admin_lancamentos
ADD COLUMN usuario_id bigint null references public.admin_usuarios(id);
