
CREATE TABLE public.admin_lancamentos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data date not null default current_date,
  descricao text not null,
  categoria text not null default 'Diversos',
  valor numeric not null default 0,
  tipo text not null default 'saida',
  status text not null default 'pendente',
  cliente_id bigint references public.admin_clientes(id) on delete set null,
  is_prolabore boolean not null default false,
  observacoes text,
  constraint admin_lancamentos_pkey primary key (id),
  constraint admin_lancamentos_tipo_check check (tipo in ('entrada', 'saida')),
  constraint admin_lancamentos_status_check check (status in ('pago', 'pendente')),
  constraint admin_lancamentos_categoria_check check (categoria in ('Pagamento de Cliente', 'Pro-labore', 'Ferramentas/Software', 'Impostos', 'Marketing', 'Diversos'))
);

ALTER TABLE public.admin_lancamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all on admin_lancamentos"
ON public.admin_lancamentos
FOR ALL
TO public
USING (true)
WITH CHECK (true);
