
CREATE TABLE public.admin_credenciais (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cliente_id bigint not null references public.admin_clientes(id) on delete cascade,
  tipo text not null, -- 'facebook', 'instagram', 'site'
  perfil text null,
  login text null,
  senha text null,
  hospedagem text null,
  url text null,
  constraint admin_credenciais_pkey primary key (id)
);

ALTER TABLE public.admin_credenciais ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all on admin_credenciais"
ON public.admin_credenciais
FOR ALL
USING (true)
WITH CHECK (true);
