// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vamuboxhirdopnnowxxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbXVib3hoaXJkb3Bubm93eHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDQyNjEsImV4cCI6MjA3NTY4MDI2MX0.Z0nLALXYHfEdQ74iGNo-BUpU8JvVXjTGPs8Z6Rz3j14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});